# Generated by Django 3.1.3 on 2021-03-29 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0010_auto_20210310_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 29, 16, 57, 30, 989666), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 29, 16, 57, 30, 989597), null=True),
        ),
    ]
