# Generated by Django 3.1.3 on 2021-03-30 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_auto_20210329_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 30, 10, 27, 4, 135360), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 10, 27, 4, 135268), null=True),
        ),
    ]
