# Generated by Django 3.1.3 on 2021-03-31 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0015_auto_20210330_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 31, 7, 10, 23, 38733), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 7, 10, 23, 38461), null=True),
        ),
    ]
