# Generated by Django 3.1.3 on 2021-02-28 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_auto_20210228_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='end_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 16, 19, 45, 677872), null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 16, 19, 45, 677781), null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='start_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 16, 19, 45, 677858), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 16, 19, 45, 679296), null=True),
        ),
        migrations.AlterField(
            model_name='teamviewertokens',
            name='expire_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 16, 19, 45, 680278), null=True),
        ),
    ]
