# Generated by Django 3.1.3 on 2021-03-10 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0023_auto_20210310_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='end_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 19, 4, 896283), null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 19, 4, 896160), null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='start_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 19, 4, 896266), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 19, 4, 897997), null=True),
        ),
        migrations.AlterField(
            model_name='teamviewertokens',
            name='expire_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 19, 4, 899053), null=True),
        ),
    ]
