# Generated by Django 3.1.3 on 2021-03-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashfree', '0002_auto_20210331_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneId',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transferId',
            field=models.CharField(max_length=20),
        ),
    ]
