# Generated by Django 3.1.3 on 2021-03-29 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20210329_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 29, 17, 8, 19, 921458), null=True),
        ),
    ]
