# Generated by Django 3.1.3 on 2021-03-30 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_auto_20210330_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 10, 43, 3, 269737), null=True),
        ),
    ]
