# Generated by Django 3.1.3 on 2021-03-31 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20210330_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 7, 10, 23, 117748), null=True),
        ),
    ]
